# Generated by Django 4.2.4 on 2023-08-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('data_nascimento', models.DateField()),
                ('cpf', models.CharField(max_length=14)),
                ('rg', models.CharField(max_length=20)),
                ('telefone', models.CharField(max_length=20)),
                ('endereco', models.CharField(max_length=255)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('cep', models.CharField(max_length=10)),
                ('uf', models.CharField(max_length=2)),
                ('nome_mae', models.CharField(max_length=100)),
                ('nome_pai', models.CharField(max_length=100)),
                ('rg_responsavel', models.CharField(max_length=20)),
                ('codigo_escola', models.CharField(max_length=20)),
                ('nome_escola', models.CharField(max_length=255)),
                ('matricula_escolar', models.CharField(max_length=20)),
                ('nivel_ensino', models.CharField(choices=[('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Superior', 'Superior')], max_length=20)),
                ('serie', models.CharField(max_length=20)),
                ('codigo_curso', models.CharField(max_length=20)),
                ('linha1', models.TextField(blank=True)),
                ('linha2', models.TextField(blank=True)),
                ('linha3', models.TextField(blank=True)),
                ('linha4', models.TextField(blank=True)),
                ('linha5', models.TextField(blank=True)),
                ('linha6', models.TextField(blank=True)),
                ('linha7', models.TextField(blank=True)),
                ('linha8', models.TextField(blank=True)),
                ('linha9', models.TextField(blank=True)),
                ('linha10', models.TextField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
