# Generated by Django 4.2.4 on 2023-09-03 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0004_contaescola_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaescola',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='contaescola_user_set', to='auth.group'),
        ),
        migrations.AddField(
            model_name='contaescola',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='contaescola',
            name='password',
            field=models.CharField(default=None, max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contaescola',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='contaescola_user_set', to='auth.permission'),
        ),
        migrations.AlterField(
            model_name='contaescola',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='contaescola',
            name='password_hash',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
    ]
