# Generated by Django 4.2.4 on 2023-09-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_contaescola_groups_contaescola_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaescola',
            name='password_hash',
            field=models.CharField(default=None, max_length=128),
            preserve_default=False,
        ),
    ]
