# Generated by Django 4.2.4 on 2023-09-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_contaescola_password_hash'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contaescola',
            name='password_hash',
            field=models.CharField(default='', max_length=128),
        ),
    ]
