# Generated by Django 4.2.4 on 2023-09-03 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_contaescola_password_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contaescola',
            name='password_hash',
        ),
        migrations.AlterField(
            model_name='contaescola',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
