# Generated by Django 4.2.4 on 2023-09-03 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_remove_contaescola_password_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contaescola',
            name='is_staff',
            field=models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status'),
        ),
    ]
