# Generated by Django 4.2.4 on 2023-11-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0013_acessoaluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='acessoaluno',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='acessoaluno',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='acessoaluno_user_set', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='acessoaluno',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='acessoaluno_user_set', to='auth.permission'),
        ),
    ]
