# Generated by Django 4.2.4 on 2023-11-19 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_acessoaluno_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoaluno',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
