# Generated by Django 4.2.4 on 2023-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_acessoaluno_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acessoaluno',
            name='cpf',
            field=models.CharField(max_length=11, unique=True),
        ),
        migrations.AlterField(
            model_name='acessoaluno',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
